[book]
authors = ["Alumet contributors"]
language = "en"
src = "src"
title = "ALUMET user guide"

[output.html]
additional-css = ["addons/pagetoc.css"]
additional-js = ["addons/pagetoc.js", "addons/mermaid.min.js", "addons/mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
